baseURL = "https://triparishok.org/"
locale = "en-US"
title = "Tri-Parish Catholic Community"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  noindex = true
  description = "The Catholic parishes of St. Ann, Our Lady of Perpetual Help, and Mother of Sorrows."
